name: sm8450 twrp prebuilts build process

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout kernel repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip tar clang

      - name: Build everything
        run: |
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 kernel_platform/prebuilts-master/clang/host/linux-x86 --depth=1
          ./build_kernel_GKI.sh g0q_gbl_openx
          
      - name: Generate release file
        id: files
        run: |
          basedir=$(pwd)
          tag=$(date +'%Y%m%d%H%M%S')
          date=$(date +'%d-%m-%Y')
          cd out && zip -r prebuilts.zip * && cd $basedir
          echo ::set-output name=zip::`find -name prebuilts.zip`
          echo ::set-output name=tag::$tag
          echo ::set-output name=date::$date
      - name: Update current version and create log
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{github.ref}} --ff-only
          git tag ${{ steps.files.outputs.tag }}
